resources:
- name: user-manager-spring
  type: git
  source:
    uri: https://github.com/pivotal-tokyo/user-manager-spring
    branch: master

jobs:
- name: test
  plan:
  - get: user-manager-spring
    trigger: true
  - task: run-server-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: tokyobeach/user_manager_spring}
      inputs:
      - name: user-manager-spring
      run:
        dir: user-manager-spring
        path: make
        args:
        - unit-ci
